import type { NextPage } from "next";
import Head from "next/head";

const Cart: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Carrinho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Carrinho</h1>
    </div>
  );
};

export default Cart;
