import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus
          sunt ratione molestiae recusandae magni corporis iure voluptas aut qui
          praesentium.
        </p>
      </main>
    </div>
  );
};

export default Home;
