import type { NextPage } from "next";
import Head from "next/head";

const Products: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nossos produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Nossos produtos</h1>
    </div>
  );
};

export default Products;
